url : "http://127.0.0.1:"  #host machine IP
port : "33333" #the port that will send from v2xhub to carma cloud ## initally was 23665
base_req : "/carmacloud/tcmreq" #URL for traffic control request
base_ack : "/carmacloud/tcmack"  #URL for traffic control acknowlegement.
list : "true" #list determines how the TCMs will be sent in response. "true" means a list of TCMs are sent. "false" means one at a time
fetchtime : 15  # number of days back when a geofence is valid
method : "POST"
webip : "WebServicePort"
