#Frame ID of the frame with +x aligned to vehicle heading and +z into the ground
heading_frame : "ned_heading"
# Frame ID of the base_link frame
base_link_frame : "base_link"
# Frame ID of the map frame
map_frame : "map"
