/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_dot_fhwa_saxton_carma_message_factory_MapMessage */

#ifndef _Included_gov_dot_fhwa_saxton_carma_message_factory_MapMessage
#define _Included_gov_dot_fhwa_saxton_carma_message_factory_MapMessage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gov_dot_fhwa_saxton_carma_message_factory_MapMessage
 * Method:    decodeMap
 * Signature: ([BLjava/lang/Object;[I[I[I[I[I[I[[I)I
 */
JNIEXPORT jint JNICALL Java_gov_dot_fhwa_saxton_carma_message_factory_MapMessage_decodeMap
  (JNIEnv *, jobject, jbyteArray, jobject, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
