/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_dot_fhwa_saxton_carma_message_BSMFactory */

#ifndef _Included_gov_dot_fhwa_saxton_carma_message_BSMFactory
#define _Included_gov_dot_fhwa_saxton_carma_message_BSMFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gov_dot_fhwa_saxton_carma_message_BSMFactory
 * Method:    encode_BSM
 * Signature: (I[IIIII[IIIII[I[I[I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_gov_dot_fhwa_saxton_carma_message_BSMFactory_encode_1BSM
  (JNIEnv *, jclass, jint, jintArray, jint, jint, jint, jint, jintArray, jint, jint, jint, jint, jintArray, jintArray, jintArray);

/*
 * Class:     gov_dot_fhwa_saxton_carma_message_BSMFactory
 * Method:    decode_BSM
 * Signature: ([BLjava/lang/Object;[BLjava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;[BLjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_gov_dot_fhwa_saxton_carma_message_BSMFactory_decode_1BSM
  (JNIEnv *, jclass, jbyteArray, jobject, jbyteArray, jobject, jobject, jobject, jbyteArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
