/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gov_dot_fhwa_saxton_carma_message_factory_MobilityAckMessage */

#ifndef _Included_gov_dot_fhwa_saxton_carma_message_factory_MobilityAckMessage
#define _Included_gov_dot_fhwa_saxton_carma_message_factory_MobilityAckMessage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gov_dot_fhwa_saxton_carma_message_factory_MobilityAckMessage
 * Method:    encode_MobilityAck
 * Signature: ([C[C[C[CI[C)[B
 */
JNIEXPORT jbyteArray JNICALL Java_gov_dot_fhwa_saxton_carma_message_factory_MobilityAckMessage_encode_1MobilityAck
  (JNIEnv *, jobject, jcharArray, jcharArray, jcharArray, jcharArray, jint, jcharArray);

/*
 * Class:     gov_dot_fhwa_saxton_carma_message_factory_MobilityAckMessage
 * Method:    decode_MobilityAck
 * Signature: ([B[C[C[C[CLjava/lang/Object;[C)I
 */
JNIEXPORT jint JNICALL Java_gov_dot_fhwa_saxton_carma_message_factory_MobilityAckMessage_decode_1MobilityAck
  (JNIEnv *, jobject, jbyteArray, jcharArray, jcharArray, jcharArray, jcharArray, jobject, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
