/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../test_bsm/J2735_201603.asn1"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -gen-PER`
 */

#include "IntersectionAccessPoint.h"

asn_per_constraints_t asn_PER_type_IntersectionAccessPoint_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  2 }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_IntersectionAccessPoint_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IntersectionAccessPoint, choice.lane),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneID,
		0,
		0,	/* Defer constraints checking to the member type */
		0,	/* OER is not compiled, use -gen-OER */
		0,	/* No PER visible constraints */
		0,
		"lane"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IntersectionAccessPoint, choice.approach),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ApproachID,
		0,
		0,	/* Defer constraints checking to the member type */
		0,	/* OER is not compiled, use -gen-OER */
		0,	/* No PER visible constraints */
		0,
		"approach"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IntersectionAccessPoint, choice.connection),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneConnectionID,
		0,
		0,	/* Defer constraints checking to the member type */
		0,	/* OER is not compiled, use -gen-OER */
		0,	/* No PER visible constraints */
		0,
		"connection"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_IntersectionAccessPoint_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* lane */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* approach */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* connection */
};
asn_CHOICE_specifics_t asn_SPC_IntersectionAccessPoint_specs_1 = {
	sizeof(struct IntersectionAccessPoint),
	offsetof(struct IntersectionAccessPoint, _asn_ctx),
	offsetof(struct IntersectionAccessPoint, present),
	sizeof(((struct IntersectionAccessPoint *)0)->present),
	asn_MAP_IntersectionAccessPoint_tag2el_1,
	3,	/* Count of tags in the map */
	0,
	3	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_IntersectionAccessPoint = {
	"IntersectionAccessPoint",
	"IntersectionAccessPoint",
	&asn_OP_CHOICE,
	CHOICE_constraint,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No OER visible constraints */
	&asn_PER_type_IntersectionAccessPoint_constr_1,
	asn_MBR_IntersectionAccessPoint_1,
	3,	/* Elements count */
	&asn_SPC_IntersectionAccessPoint_specs_1	/* Additional specs */
};

