/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../test_bsm/J2735_201603.asn1"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -gen-PER`
 */

#include "Node-LLmD-64b.h"

asn_TYPE_member_t asn_MBR_Node_LLmD_64b_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Node_LLmD_64b, lon),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Longitude,
		0,
		0,	/* Defer constraints checking to the member type */
		0,	/* OER is not compiled, use -gen-OER */
		0,	/* No PER visible constraints */
		0,
		"lon"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Node_LLmD_64b, lat),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Latitude,
		0,
		0,	/* Defer constraints checking to the member type */
		0,	/* OER is not compiled, use -gen-OER */
		0,	/* No PER visible constraints */
		0,
		"lat"
		},
};
static const ber_tlv_tag_t asn_DEF_Node_LLmD_64b_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Node_LLmD_64b_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* lon */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* lat */
};
asn_SEQUENCE_specifics_t asn_SPC_Node_LLmD_64b_specs_1 = {
	sizeof(struct Node_LLmD_64b),
	offsetof(struct Node_LLmD_64b, _asn_ctx),
	asn_MAP_Node_LLmD_64b_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Node_LLmD_64b = {
	"Node-LLmD-64b",
	"Node-LLmD-64b",
	&asn_OP_SEQUENCE,
	SEQUENCE_constraint,
	asn_DEF_Node_LLmD_64b_tags_1,
	sizeof(asn_DEF_Node_LLmD_64b_tags_1)
		/sizeof(asn_DEF_Node_LLmD_64b_tags_1[0]), /* 1 */
	asn_DEF_Node_LLmD_64b_tags_1,	/* Same as above */
	sizeof(asn_DEF_Node_LLmD_64b_tags_1)
		/sizeof(asn_DEF_Node_LLmD_64b_tags_1[0]), /* 1 */
	0,	/* No OER visible constraints */
	0,	/* No PER visible constraints */
	asn_MBR_Node_LLmD_64b_1,
	2,	/* Elements count */
	&asn_SPC_Node_LLmD_64b_specs_1	/* Additional specs */
};

