#!/bin/bash

if [ "$#" -ne 3 ]; then
    echo "Incorrect inputs: Input must be of form <this template_package path> <package name> <path to new package parent folder>"
    exit 2
fi

template_package_path = $1

if [[ ! -d ${template_package_path} ]] then
    echo "template_package directory ${template_package_path} DOES NOT exists." 
    exit 2
fi


package_name = $2

if [[ -z ${package_name} ]] then
    echo "Package name not provided." 
    exit 2
fi

if [[ "${package_name}" =~ [^a-zA-Z0-9_\ ] ]]; then
  echo "Package name ${package_name} contains invalid characters. Must be alpha numeric with any spaces as underscores."
  exit 2
fi

package_parent_path = $3

if [[ ! -d ${package_parent_path} ]] then
    echo "New package parent path directory ${package_parent_path} DOES NOT exists." 
    exit 2
fi

cp ${template_package_path} ${package_parent_path}/${package_name}

cd ${package_parent_path}/${package_name}

current_year = date +"%Y"

find . -type f -exec sed -i "s/<SUB><package_name>/${package_name}/g" {} \;
find . -type f -exec sed -i "s/<SUB><year>/${current_year}/g" {} \;


