/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../test_bsm/J2735_201603.asn1"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -gen-PER`
 */

#ifndef	_AxleLocation_H_
#define	_AxleLocation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AxleLocation */
typedef long	 AxleLocation_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AxleLocation_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AxleLocation;
asn_struct_free_f AxleLocation_free;
asn_struct_print_f AxleLocation_print;
asn_constr_check_f AxleLocation_constraint;
ber_type_decoder_f AxleLocation_decode_ber;
der_type_encoder_f AxleLocation_encode_der;
xer_type_decoder_f AxleLocation_decode_xer;
xer_type_encoder_f AxleLocation_encode_xer;
per_type_decoder_f AxleLocation_decode_uper;
per_type_encoder_f AxleLocation_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AxleLocation_H_ */
#include <asn_internal.h>
