/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpB"
 * 	found in "../test_bsm/J2735_201603.asn1"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -gen-PER`
 */

#ifndef	_Day_H_
#define	_Day_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Day */
typedef long	 Day_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Day_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Day;
asn_struct_free_f Day_free;
asn_struct_print_f Day_print;
asn_constr_check_f Day_constraint;
ber_type_decoder_f Day_decode_ber;
der_type_encoder_f Day_encode_der;
xer_type_decoder_f Day_decode_xer;
xer_type_encoder_f Day_encode_xer;
per_type_decoder_f Day_decode_uper;
per_type_encoder_f Day_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Day_H_ */
#include <asn_internal.h>
