/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpC"
 * 	found in "../test_bsm/J2735_201603.asn1"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -gen-PER`
 */

#ifndef	_EmissionType_H_
#define	_EmissionType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EmissionType {
	EmissionType_typeA	= 0,
	EmissionType_typeB	= 1,
	EmissionType_typeC	= 2,
	EmissionType_typeD	= 3,
	EmissionType_typeE	= 4
	/*
	 * Enumeration is extensible
	 */
} e_EmissionType;

/* EmissionType */
typedef long	 EmissionType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_EmissionType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EmissionType;
extern const asn_INTEGER_specifics_t asn_SPC_EmissionType_specs_1;
asn_struct_free_f EmissionType_free;
asn_struct_print_f EmissionType_print;
asn_constr_check_f EmissionType_constraint;
ber_type_decoder_f EmissionType_decode_ber;
der_type_encoder_f EmissionType_encode_der;
xer_type_decoder_f EmissionType_decode_xer;
xer_type_encoder_f EmissionType_encode_xer;
per_type_decoder_f EmissionType_decode_uper;
per_type_encoder_f EmissionType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EmissionType_H_ */
#include <asn_internal.h>
