/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../test_bsm/J2735_201603.asn1"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -gen-PER`
 */

#ifndef	_IntersectionID_H_
#define	_IntersectionID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IntersectionID */
typedef long	 IntersectionID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_IntersectionID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_IntersectionID;
asn_struct_free_f IntersectionID_free;
asn_struct_print_f IntersectionID_print;
asn_constr_check_f IntersectionID_constraint;
ber_type_decoder_f IntersectionID_decode_ber;
der_type_encoder_f IntersectionID_encode_der;
xer_type_decoder_f IntersectionID_decode_xer;
xer_type_encoder_f IntersectionID_encode_xer;
per_type_decoder_f IntersectionID_decode_uper;
per_type_encoder_f IntersectionID_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _IntersectionID_H_ */
#include <asn_internal.h>
