/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpB"
 * 	found in "../test_bsm/J2735_201603.asn1"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -gen-PER`
 */

#ifndef	_MinTimetoChange_H_
#define	_MinTimetoChange_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MinTimetoChange */
typedef long	 MinTimetoChange_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_MinTimetoChange_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_MinTimetoChange;
asn_struct_free_f MinTimetoChange_free;
asn_struct_print_f MinTimetoChange_print;
asn_constr_check_f MinTimetoChange_constraint;
ber_type_decoder_f MinTimetoChange_decode_ber;
der_type_encoder_f MinTimetoChange_encode_der;
xer_type_decoder_f MinTimetoChange_decode_xer;
xer_type_encoder_f MinTimetoChange_encode_xer;
per_type_decoder_f MinTimetoChange_decode_uper;
per_type_encoder_f MinTimetoChange_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MinTimetoChange_H_ */
#include <asn_internal.h>
