/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../test_bsm/J2735_201603.asn1"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -gen-PER`
 */

#ifndef	_PersonalClusterRadius_H_
#define	_PersonalClusterRadius_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PersonalClusterRadius */
typedef long	 PersonalClusterRadius_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PersonalClusterRadius_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PersonalClusterRadius;
asn_struct_free_f PersonalClusterRadius_free;
asn_struct_print_f PersonalClusterRadius_print;
asn_constr_check_f PersonalClusterRadius_constraint;
ber_type_decoder_f PersonalClusterRadius_decode_ber;
der_type_encoder_f PersonalClusterRadius_encode_der;
xer_type_decoder_f PersonalClusterRadius_decode_xer;
xer_type_encoder_f PersonalClusterRadius_encode_xer;
per_type_decoder_f PersonalClusterRadius_decode_uper;
per_type_encoder_f PersonalClusterRadius_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PersonalClusterRadius_H_ */
#include <asn_internal.h>
