/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../test_bsm/J2735_201603.asn1"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -gen-PER`
 */

#ifndef	_SignalRequestMessage_H_
#define	_SignalRequestMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MinuteOfTheYear.h"
#include "DSecond.h"
#include "DSRC_MsgCount.h"
#include "RequestorDescription.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SignalRequestList;
struct RegionalExtension;

/* SignalRequestMessage */
typedef struct SignalRequestMessage {
	MinuteOfTheYear_t	*timeStamp	/* OPTIONAL */;
	DSecond_t	 second;
	DSRC_MsgCount_t	*sequenceNumber	/* OPTIONAL */;
	struct SignalRequestList	*requests	/* OPTIONAL */;
	RequestorDescription_t	 requestor;
	struct SignalRequestMessage__regional {
		A_SEQUENCE_OF(struct RegionalExtension) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignalRequestMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignalRequestMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_SignalRequestMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_SignalRequestMessage_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SignalRequestList.h"
#include "RegionalExtension.h"

#endif	/* _SignalRequestMessage_H_ */
#include <asn_internal.h>
