/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../test_bsm/J2735_201603.asn1"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -gen-PER`
 */

#ifndef	_VehicleIdent_H_
#define	_VehicleIdent_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DescriptiveName.h"
#include "VINstring.h"
#include <IA5String.h>
#include "VehicleType.h"
#include "VehicleGroupAffected.h"
#include "ResponderGroupAffected.h"
#include "IncidentResponseEquipment.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VehicleIdent__vehicleClass_PR {
	VehicleIdent__vehicleClass_PR_NOTHING,	/* No components present */
	VehicleIdent__vehicleClass_PR_vGroup,
	VehicleIdent__vehicleClass_PR_rGroup,
	VehicleIdent__vehicleClass_PR_rEquip
} VehicleIdent__vehicleClass_PR;

/* Forward declarations */
struct VehicleID;

/* VehicleIdent */
typedef struct VehicleIdent {
	DescriptiveName_t	*name	/* OPTIONAL */;
	VINstring_t	*vin	/* OPTIONAL */;
	IA5String_t	*ownerCode	/* OPTIONAL */;
	struct VehicleID	*id	/* OPTIONAL */;
	VehicleType_t	*vehicleType	/* OPTIONAL */;
	struct VehicleIdent__vehicleClass {
		VehicleIdent__vehicleClass_PR present;
		union VehicleIdent__vehicleClass_u {
			VehicleGroupAffected_t	 vGroup;
			ResponderGroupAffected_t	 rGroup;
			IncidentResponseEquipment_t	 rEquip;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *vehicleClass;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleIdent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleIdent;
extern asn_SEQUENCE_specifics_t asn_SPC_VehicleIdent_specs_1;
extern asn_TYPE_member_t asn_MBR_VehicleIdent_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VehicleID.h"

#endif	/* _VehicleIdent_H_ */
#include <asn_internal.h>
