/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "../test_bsm/J2735_201603.asn1"
 * 	`asn1c -pdu=MessageFrame -fcompound-names -gen-PER`
 */

#ifndef	_VehicleStatusRequest_H_
#define	_VehicleStatusRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VehicleStatusDeviceTypeTag.h"
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleStatusRequest */
typedef struct VehicleStatusRequest {
	VehicleStatusDeviceTypeTag_t	 dataType;
	long	*subType	/* OPTIONAL */;
	long	*sendOnLessThenValue	/* OPTIONAL */;
	long	*sendOnMoreThenValue	/* OPTIONAL */;
	BOOLEAN_t	*sendAll	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleStatusRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleStatusRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_VehicleStatusRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_VehicleStatusRequest_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleStatusRequest_H_ */
#include <asn_internal.h>
