#
# AbortActiveRoute.srv
# 
# Service provided by RouteManager node. Aborts the currently active route.
# Returns an error message if no route is active
#
# @version 0.1
#

# Request
---
# Response
# An enumeration representing a service execution error as defined in the route design document.
uint8 error_status

# enumeration values for errorStatus:
uint8 NO_ERROR=0
uint8 NO_ACTIVE_ROUTE=1
#					<other values reserved for future expansion>