#
# GetAvailableRoutes.srv
# 
# Provided by the route manager node. Returns a list of available routes.
#
# @author Michael McConnell
# @version 0.1
#

# Request - No arguments

---
# Response

# A list of available routes
# For efficiency the routes provided in this list contain only a list of empty segments
cav_msgs/Route[] availableRoutes

