#
# PluginList.srv
# 
# Provided by the Guidance node. Returns a list of plugins depending on which
# service is providing this message
#
# @author Kyle Rush
# @version 0.1
#

# Request - No arguments

---
# Response

# A list of available plugins
cav_msgs/Plugin[] plugins
