#
# Guidance Activate Service Message
# 
# A command from the user to activate or deactivate the Guidance component
#
# @author Kyle Rush
# @version 0.1
#

# activate or deactivate the Guidance component
bool guidance_active

---
# Response
bool guidance_status
