# SetLights.srv

# Request - set the light values


# This should contain the desired state of all lights, not just the ones
# intended to be changed
cav_msgs/LightBarStatus set_state

---

# Response - no Response