#!/bin/bash

echo "Building $IMAGE_NAME"

docker build --no-cache -t $IMAGE_NAME \
    --build-arg VERSION="$DOCKER_TAG" \
    --build-arg VCS_REF=`git rev-parse --short HEAD` \
    --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` .
    