#include "carma_cooperative_perception/sdsm_to_detection_list_node.hpp"

#include <rclcpp_components/register_node_macro.hpp>

RCLCPP_COMPONENTS_REGISTER_NODE(carma_cooperative_perception::SdsmToDetectionListNode)
