execution_frequency_hz: 10.0
# Number of occurence to promote a track to be confirmed.
# For example: Occurence (Count 1) + Occurence (Count 2) 
# + Miss (Count 1) + Occurence (Count 2) + Occurence (Count 3) 
# will make the Tentative Track into a Confirmed Track.
track_promotion_threshold: 3

# Number of consecutive misses or non-occurence to 
# happen for a confirmed track to be removed.
# Any time, a confirmed track gets a new occurrence,
# it's counter updates to this value
# For example if 10, a confirmed track will only be removed
# after 10 "consecutive" non-occurence to be removed
track_removal_threshold: 10

# All tentative and confirmed tracks are removed at 0 counter
