# Whether to overwrite the default covariance values with those specified below
overwrite_covariance: true

##################################################
# NONE of the covariance values can be set to zero!
##################################################

# Pose position covariance values (in meters^2)
# These represent uncertainty in position measurements
pose_covariance_x: 0.02  # X-axis position uncertainty (lateral)
pose_covariance_y: 0.02  # Y-axis position uncertainty (longitudinal)
pose_covariance_z: 0.02  # Z-axis position uncertainty (vertical)

# Pose orientation covariance value (in radians^2)
# 10% error in yaw angle, which is (0.1 * 2 pi) ^ 2 = 0.394384
pose_covariance_yaw: 0.394384  # Yaw angle uncertainty (heading)

# Twist linear velocity covariance values (in (m/s)^2)
# These represent uncertainty in velocity measurements
twist_covariance_x: 0.005  # X-axis velocity uncertainty
twist_covariance_z: 0.005  # Z-axis velocity uncertainty

# Twist angular velocity covariance value (in (rad/s)^2)
twist_covariance_yaw: 0.005  # Yaw angular velocity uncertainty

# True to enable adding offsets to the pose of the detected object generated from the SDSM
adjust_pose: False
# Meters in map frame
x_offset: 7.5
# Meters in map frame
y_offset: -0.7
# Degrees in map frame, a.k.a positive is counter-clockwise
yaw_offset: 0.0

# List (String): Only process SDSMs from these source IDs
# NOTE: CARMA Streets sends SDSMs only 4 chars between indices inclusive [3:6]:
# if source_id = "rsu_1234", id encoded in SDSM is "1234"
# if source_id = "infra_1234", id encoded in SDSM is "a_12"
# if source_id = "rsu_1234567", id encoded in SDSM is "1234"
# List must NOT be empty. "*" to allow from any source ids.
source_ids: ["1234", "9945", "9709"]

# List (Int): Filter SDSMs to process using the equipment types
# UNKNOWN = 0, RSU = 1, OBU = 2, VRU = 3
# List must NOT be empty. 99 to allow from any equipment ids.
equipment_types: [1]
