# Double: multiplier to apply to the maximum allowable vehicle deceleration limit so we plan under our capabilities
vehicle_decel_limit_multiplier : 0.65

# Double: multiplier to apply to the maximum allowable vehicle acceleration limit so we plan under our capabilities
vehicle_accel_limit_multiplier : 0.65

# Double: A buffer before of the stopping location which will still be considered a valid stop. Units in meters
stop_line_buffer : 10.0

# String: The name to use for this plugin during comminications with the arbitrator
strategic_plugin_name : stop_and_dwell_strategic_plugin

# String: The name of the tactical plugin to use for Lane Following trajectory planning
lane_following_plugin_name : inlanecruising_plugin

# String: The name of the plugin to use for stop and wait trajectory planning
stop_and_wait_plugin_name : stop_and_wait_plugin
