# Pose and speed publication rate (Hz)
# Recommended: Match with controller's frequency
pose_pub_rate: 30.0

# When speed is low, the simulator struggles to 
# move the car forward consistently and the 
# car may oscillate back and forth. Increase to help
# avoid this issue.It means to consider
# the next trajectory point that is traj_idx_buffer
# further ahead in the trajectory. [0, inf]
traj_idx_buffer: 0
