#
# MAP.msg
#
# J2735 2016 message format.
#
# @author Mae Fromm
# @version 0.1
#
# TODO: Discuss the fields, types, and referenced msg files to use. 

## MAP.msg content:
#- time_stamp (optional)
#- msg_issue_revision
#- layer_type (optional)
#- layer_id (optional)
#- Intersections * (IntersectionGeometryList.msg)
#- RoadSegments *  (RoadSegmentList.msg)
#- DataParameters * (DataParameters.msg)
#- RestrictionList * (RestrictionClassList.msg)
#- Regional * (Regional.msg) 
