# GetDriversWithCapabilities.srv
#
# Returns a list of drivers that match the specified category AND provide ALL of the requested capabilities.
# If a driver provides capabilities that are not requested, they will be ignored (no penalty for a driver
# that is "over-qualified").
#

##### Request #####

# category is an enum indicating the general type of driver being requested
uint32				category
# constant enum values to be used for category:
uint32				CONTROLLER = 1
uint32				COMMS = 2
uint32				POSITION = 3
uint32				SENSOR = 4
uint32				CAN = 5

# capabilities is a list of descriptive strings

# TODO: tell reader where to find the authoritative list of all capabilities from which to choose
string[]			capabilities
---

##### Response #####

# a list of drivers that meet the given criteria
string[]			driver_names
