#
# GetRegisteredPlugins.srv
# 
# Provided by the Guidance node. Returns a list of discovered, instantiated
# and registered IPlugin instances
#
# @author Kyle Rush
# @version 0.1
#

# Request - No arguments

---
# Response

# A list of registered plugins
cav_msgs/Plugin[] plugins