#
# SetActiveRoute.srv
# 
# Service provided by RouteManager node. Sets a route with the 
# specified id as the active route.
#
# @author Michael McConnell
# @version 0.1
#

# Request
# The id of the route to select
string routeID
---
# Response
# An enumeration representing a service execution error as defined in the route design document.
uint8 errorStatus

# enumeration values for errorStatus:
uint8				NO_ERROR=0
uint8				NO_ROUTE=1
#					<other values reserved for future expansion>